/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Categories.java
 *
 * Created on Nov 1, 2017, 2:10:32 PM
 */

/**
 *
 * @author Admin
 */
public class Categories extends javax.swing.JFrame {

    /** Creates new form Categories */
    public Categories() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        b1 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Choose any THREE of the given quiz categories");

        r1.setText("Entertainment Quiz");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        r2.setText("History Quiz");

        r3.setText("Sports Quiz");

        r4.setText("G.K Quiz");

        r5.setText("Technology Quiz");

        b1.setText("Submit Your Choice");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("Move to Questions");
        b2.setEnabled(false);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(r1)
                                .addGap(26, 26, 26)
                                .addComponent(r2)
                                .addGap(28, 28, 28)
                                .addComponent(r3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b1)
                                    .addComponent(r4))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r5)
                                    .addComponent(b2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r1)
                    .addComponent(r2)
                    .addComponent(r3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r4)
                    .addComponent(r5))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b2))
                .addGap(43, 43, 43)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        l1.setText("Your choices have been submitted successfully.");
        l2.setText("Now you will get question set accordingly.");
    b2.setEnabled(true);
    b1.setEnabled(false);
    if(r1.isSelected()==true && r2.isSelected()==true && r3.isSelected()==true)
   {
       r4.setEnabled(false);
       r5.setEnabled(false);
   }
    if(r1.isSelected()==true && r2.isSelected()==true && r4.isSelected()==true)
   {
       r3.setEnabled(false);
       r5.setEnabled(false);
   }
    if(r1.isSelected()==true && r2.isSelected()==true && r5.isSelected()==true)
   {
       r4.setEnabled(false);
       r3.setEnabled(false);
   }
    if(r1.isSelected()==true && r3.isSelected()==true && r5.isSelected()==true)
   {
       r4.setEnabled(false);
       r2.setEnabled(false);
   }
    if(r1.isSelected()==true && r4.isSelected()==true && r5.isSelected()==true)
   {
       r2.setEnabled(false);
       r3.setEnabled(false);
   }
    if(r1.isSelected()==true && r4.isSelected()==true && r3.isSelected()==true)
   {
       r2.setEnabled(false);
       r5.setEnabled(false);
   }
    if(r5.isSelected()==true && r2.isSelected()==true && r3.isSelected()==true)
   {
       r4.setEnabled(false);
       r1.setEnabled(false);
   }
    if(r4.isSelected()==true && r2.isSelected()==true && r5.isSelected()==true)
   {
       r1.setEnabled(false);
       r3.setEnabled(false);
   }
    if(r5.isSelected()==true && r4.isSelected()==true && r3.isSelected()==true)
   {
       r2.setEnabled(false);
       r1.setEnabled(false);
   }
    if(r4.isSelected()==true && r2.isSelected()==true && r3.isSelected()==true)
   {
       r1.setEnabled(false);
       r5.setEnabled(false);
   }
}//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
   if(r1.isSelected()==true && r2.isSelected()==true && r3.isSelected()==true)
   {
       new Q11().setVisible(true);
       dispose();
   }
   if(r1.isSelected()==true && r2.isSelected()==true && r4.isSelected()==true)
   {
       new Q21().setVisible(true);
       dispose();
   }
   if(r1.isSelected()==true && r2.isSelected()==true && r5.isSelected()==true)
   {
       new Q31().setVisible(true);
       dispose();
   }
   if(r1.isSelected()==true && r3.isSelected()==true && r5.isSelected()==true)
   {
       new Q41().setVisible(true);
       dispose();
   }
   if(r1.isSelected()==true && r4.isSelected()==true && r5.isSelected()==true)
   {
       new Q51().setVisible(true);
       dispose();
   }
   if(r1.isSelected()==true && r3.isSelected()==true && r4.isSelected()==true)
   {
       new Q61().setVisible(true);
       dispose();
   }
   if(r2.isSelected()==true && r3.isSelected()==true && r5.isSelected()==true)
   {
       new Q71().setVisible(true);
       dispose();
   }
   if(r2.isSelected()==true && r4.isSelected()==true && r5.isSelected()==true)
   {
       new Q81().setVisible(true);
       dispose();
   }
   if(r2.isSelected()==true && r3.isSelected()==true && r4.isSelected()==true)
   {
       new Q91().setVisible(true);
       dispose();
   }
   if(r3.isSelected()==true && r4.isSelected()==true && r5.isSelected()==true)
   {
       new Q01().setVisible(true);
       dispose();
   }
}//GEN-LAST:event_b2ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    // End of variables declaration//GEN-END:variables

}
