/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ins.java
 *
 * Created on Nov 8, 2017, 11:19:20 PM
 */

/**
 *
 * @author Admin
 */
public class ins extends javax.swing.JFrame {

    /** Creates new form ins */
    public ins() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("for that next question");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(120, 210, 180, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("for that question answered");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(100, 250, 200, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("All the best and obtain maximum points");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 420, 260, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("points for that next question");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(120, 290, 180, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("For every wrong answer you loose 1 point");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 70, 280, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("For every correct answer you get 1 point");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 50, 270, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Total Score is updated and informed after answering the question");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 90, 390, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("There are 10 Questions in a question set for a constestant");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 110, 350, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("There are 5 categories given out of which only 3 has to be chosen");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 130, 390, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Depending upon the choices you get the question set accordingly");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 150, 390, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("If you skip a question & answer the next one,you would get 0.5 points ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 190, 420, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("If you skip two question & answer the third one,you would get 0.25 points ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 230, 430, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("If you skip three questions & answer the one next to it you would get no ");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 270, 410, 14);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("At the end for 3 to 5 Correct answers,you get 1 point as bonus");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 330, 380, 14);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setText("At the end for 6 to 9 Correct answers,you get 2 points as bonus");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(40, 350, 380, 14);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel18.setForeground(new java.awt.Color(255, 255, 0));
        jLabel18.setText("At the end for all 10 Correct answers,you get 3 points as bonus");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(40, 370, 380, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Note that Once you pass the question you can't visit it again");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 400, 360, 14);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 450, 90, 23);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setText("Instructions");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(190, 20, 69, 14);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logonap.PNG"))); // NOI18N
        jLabel20.setText("jLabel20");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(420, 410, 70, 70);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lar1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 560, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new face().setVisible(true);
        dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
