
import gentechquiz.Main;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ques21.java
 *
 * Created on Nov 8, 2017, 8:06:52 PM
 */

/**
 *
 * @author Admin
 */
public class ques21 extends javax.swing.JFrame {

    /** Creates new form ques21 */
    public ques21() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        r1 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        r1.setBackground(new java.awt.Color(0, 51, 204));
        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Tahoma", 1, 11));
        r1.setForeground(new java.awt.Color(255, 255, 0));
        r1.setText("The Guide");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        jPanel1.add(r1);
        r1.setBounds(250, 90, 90, 23);

        r3.setBackground(new java.awt.Color(0, 51, 204));
        buttonGroup1.add(r3);
        r3.setFont(new java.awt.Font("Tahoma", 1, 11));
        r3.setForeground(new java.awt.Color(255, 255, 0));
        r3.setText("Madhumati");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        jPanel1.add(r3);
        r3.setBounds(250, 120, 89, 23);

        r2.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Tahoma", 1, 11));
        r2.setForeground(new java.awt.Color(255, 255, 0));
        r2.setText("Mother India");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        jPanel1.add(r2);
        r2.setBounds(50, 120, 99, 23);

        r4.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup1.add(r4);
        r4.setFont(new java.awt.Font("Tahoma", 1, 11));
        r4.setForeground(new java.awt.Color(255, 255, 0));
        r4.setText("Amrapali");
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });
        jPanel1.add(r4);
        r4.setBounds(50, 90, 77, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("1.)First Indian film submitted for Oscar?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 60, 240, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("GenTech Quiz");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 20, 76, 14);

        b1.setBackground(new java.awt.Color(0, 0, 204));
        b1.setFont(new java.awt.Font("Tahoma", 1, 11));
        b1.setForeground(new java.awt.Color(255, 255, 0));
        b1.setText("Submit your answer");
        b1.setEnabled(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(125, 160, 150, 23);

        b2.setBackground(new java.awt.Color(0, 0, 204));
        b2.setFont(new java.awt.Font("Tahoma", 1, 11));
        b2.setForeground(new java.awt.Color(255, 255, 0));
        b2.setText("Next Question");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(131, 260, 130, 23);

        l1.setFont(new java.awt.Font("Tahoma", 1, 11));
        l1.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(l1);
        l1.setBounds(10, 220, 260, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logosah.PNG"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(330, 230, 70, 70);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lar1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        b1.setEnabled(true);        // TODO add your handling code here:
}//GEN-LAST:event_r1ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        b1.setEnabled(true);        // TODO add your handling code here:
}//GEN-LAST:event_r3ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        b1.setEnabled(true);        // TODO add your handling code here:
}//GEN-LAST:event_r2ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
        b1.setEnabled(true);        // TODO add your handling code here:
}//GEN-LAST:event_r4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        Main.l=Main.l+1;
        if(r2.isSelected()==true) {
            Main.m=Main.m+1;
            if(Main.k==0) {
                Main.c=Main.c+1;
                Main.k=0;
            }
            if(Main.k==1) {
                Main.c=(float) (Main.c + 0.5);
                Main.k=0;
            }
            if(Main.k==2) {
                Main.c=(float) (Main.c + 0.25);
                Main.k=0;
            }
            if(Main.k>=3) {
                Main.k=0;
            }
            l1.setText("Correct Answer.Your Total Score is "+Main.c);
            b1.setEnabled(false);
            r1.setEnabled(false);
            r2.setEnabled(false);
            r3.setEnabled(false);
            r4.setEnabled(false);
        }
        if(r1.isSelected()==true) {
            Main.c=Main.c-1;
            l1.setText("Wrong Answer.Your Total Score is "+Main.c);
            b1.setEnabled(false);
            r1.setEnabled(false);
            r2.setEnabled(false);
            r3.setEnabled(false);
            r4.setEnabled(false);
        }
        if(r3.isSelected()==true) {
            Main.c=Main.c-1;
            l1.setText("Wrong Answer.Your Total Score is "+Main.c);
            b1.setEnabled(false);
            r1.setEnabled(false);
            r2.setEnabled(false);
            r3.setEnabled(false);
            r4.setEnabled(false);
        }
        if(r4.isSelected()==true) {
            Main.c=Main.c-1;
            l1.setText("Wrong Answer.Your Total Score is "+Main.c);
            b1.setEnabled(false);
            r1.setEnabled(false);
            r2.setEnabled(false);
            r3.setEnabled(false);
            r4.setEnabled(false);
        }
}//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        new ques22().setVisible(true);
        dispose();
        if(Main.l==0) {
            Main.k=Main.k+1;
        }
        Main.l=0;
}//GEN-LAST:event_b2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ques21().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    // End of variables declaration//GEN-END:variables

}
