
import gentechquiz.Main;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * thanks.java
 *
 * Created on Nov 8, 2017, 10:43:11 PM
 */

/**
 *
 * @author Admin
 */
public class thanks extends javax.swing.JFrame {

    /** Creates new form thanks */
    public thanks() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Thanks For Playing.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 40, 120, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Hope You Had a Nice Learning Experience");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 70, 231, 14);

        b1.setBackground(new java.awt.Color(0, 0, 204));
        b1.setFont(new java.awt.Font("Tahoma", 1, 11));
        b1.setForeground(new java.awt.Color(255, 255, 0));
        b1.setText("Obtain Score");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(30, 220, 110, 23);

        b2.setBackground(new java.awt.Color(0, 0, 204));
        b2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 0));
        b2.setText("Play Again");
        b2.setEnabled(false);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(160, 220, 100, 23);

        b3.setBackground(new java.awt.Color(0, 0, 204));
        b3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 0));
        b3.setText("Exit");
        b3.setEnabled(false);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(280, 220, 70, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("(KIET 3rd year IT-B)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 350, 97, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Shashwat Singh");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 320, 89, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Yogansh Gupta");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(260, 290, 85, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Developers Team");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 260, 99, 14);

        l7.setFont(new java.awt.Font("Tahoma", 1, 11));
        l7.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(l7);
        l7.setBounds(60, 140, 280, 20);

        l5.setFont(new java.awt.Font("Tahoma", 1, 11));
        l5.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(l5);
        l5.setBounds(50, 180, 290, 20);

        l9.setFont(new java.awt.Font("Tahoma", 1, 11));
        l9.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(l9);
        l9.setBounds(50, 100, 290, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logonap.PNG"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 310, 70, 70);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lar1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        b1.setEnabled(false);
        b2.setEnabled(true);
        b3.setEnabled(true);

        l9.setText("Correct Answers given = "+Main.m);

        if(Main.a!=0) {
           
            if(Main.m>=3&&Main.m<6) {
                l7.setText("Bonus point earned is 1");
                Main.a=Main.a+1;
                

            }
            if(Main.m>=6&&Main.m<10) {
                l7.setText("Bonus point earned is 2");
                Main.a=Main.a+2;
            }
            if(Main.m==10) {
                l7.setText("Bonus point earned is 3");
                Main.a=Main.a+3;
            }
            l5.setText("Your total score in this session = "+Main.a);
            Main.a=0;
            Main.m=0;
        }
if(Main.b!=0) {
            if(Main.m>=3&&Main.m<6) {
                l7.setText("Bonus point earned is 1");
                Main.b=Main.b+1;
            }
            if(Main.m>=6&&Main.m<10) {
                l7.setText("Bonus point earned is 2");
                Main.b=Main.b+2;
            }
            if(Main.m==10) {
                l7.setText("Bonus point earned is 3");
                Main.b=Main.b+3;
            }
            l5.setText("Your total score in this session = "+Main.b);
            Main.b=0;
            Main.m=0;
        }


        if(Main.c!=0) {
            if(Main.m>=3&&Main.m<6) {
                l7.setText("Bonus point earned is 1");
                Main.c=Main.c+1;
            }
            if(Main.m>=6&&Main.m<10) {
                l7.setText("Bonus point earned is 2");
                Main.c=Main.c+2;
            }
            if(Main.m==10) {
                l7.setText("Bonus point earned is 3");
                Main.c=Main.c+3;
            }
            l5.setText("Your total score in this session = "+Main.c);
            Main.c=0;
            Main.m=0;
        }


        if(Main.d!=0) {
            if(Main.m>=3&&Main.m<6) {
                l7.setText("Bonus point earned is 1");
                Main.d=Main.d+1;
            }
            if(Main.m>=6&&Main.m<10) {
                l7.setText("Bonus point earned is 2");
                Main.d=Main.d+2;
            }
            if(Main.m==10) {
                l7.setText("Bonus point earned is 3");
                Main.d=Main.d+3;
            }
            l5.setText("Your total score in this session = "+Main.d);
            Main.d=0;
            Main.m=0;
        }


        if(Main.e!=0) {
            if(Main.m>=3&&Main.m<6) {
                l7.setText("Bonus point earned is 1");
                Main.e=Main.e+1;
            }
            if(Main.m>=6&&Main.m<10) {
                l7.setText("Bonus point earned is 2");
                Main.e=Main.e+2;
            }
            if(Main.m==10) {
                l7.setText("Bonus point earned is 3");
                Main.e=Main.e+3;
            }
            l5.setText("Your total score in this session = "+Main.e);
            Main.e=0;
            Main.m=0;
        }


        if(Main.f!=0) {
            if(Main.m>=3&&Main.m<6) {
                l7.setText("Bonus point earned is 1");
                Main.f=Main.f+1;
            }
            if(Main.m>=6&&Main.m<10) {
                l7.setText("Bonus point earned is 2");
                Main.f=Main.f+2;
            }
            if(Main.m==10) {
                l7.setText("Bonus point earned is 3");
                Main.f=Main.f+3;
            }
            l5.setText("Your total score in this session = "+Main.f);
            Main.f=0;
            Main.m=0;
        }


        if(Main.g!=0) {
            if(Main.m>=3&&Main.m<6) {
                l7.setText("Bonus point earned is 1");
                Main.g=Main.g+1;
            }
            if(Main.m>=6&&Main.m<10) {
                l7.setText("Bonus point earned is 2");
                Main.g=Main.g+2;
            }
            if(Main.m==10) {
                l7.setText("Bonus point earned is 3");
                Main.g=Main.g+3;
            }
            l5.setText("Your total score in this session = "+Main.g);
            Main.g=0;
            Main.m=0;
        }


        if(Main.h!=0) {
            if(Main.m>=3&&Main.m<6) {
                l7.setText("Bonus point earned is 1");
                Main.h=Main.h+1;
            }
            if(Main.m>=6&&Main.m<10) {
                l7.setText("Bonus point earned is 2");
                Main.h=Main.h+2;
            }
            if(Main.m==10) {
                l7.setText("Bonus point earned is 3");
                Main.h=Main.h+3;
            }
            l5.setText("Your total score in this session = "+Main.h);
            Main.h=0;
            Main.m=0;
        }


        if(Main.i!=0) {
            if(Main.m>=3&&Main.m<6) {
                l7.setText("Bonus point earned is 1");
                Main.i=Main.i+1;
            }
            if(Main.m>=6&&Main.m<10) {
                l7.setText("Bonus point earned is 2");
                Main.i=Main.i+2;
            }
            if(Main.m==10) {
                l7.setText("Bonus point earned is 3");
                Main.i=Main.i+3;
            }
            l5.setText("Your total score in this session = "+Main.i);
            Main.i=0;
            Main.m=0;
        }


        if(Main.j!=0) {
            if(Main.m>=3&&Main.m<6) {
                l7.setText("Bonus point earned is 1");
                Main.j=Main.j+1;
            }
            if(Main.m>=6&&Main.m<10) {
                l7.setText("Bonus point earned is 2");
                Main.j=Main.j+2;
            }
            if(Main.m==10) {
                l7.setText("Bonus point earned is 3");
                Main.j=Main.j+3;
            }
            l5.setText("Your total score in this session = "+Main.j);
            Main.j=0;
            Main.m=0;
        }


       
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        new face().setVisible(true);
        dispose();
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        System.exit(0);
}//GEN-LAST:event_b3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thanks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables

}
