/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * topics.java
 *
 * Created on Nov 8, 2017, 10:58:19 PM
 */

/**
 *
 * @author Admin
 */
public class topics extends javax.swing.JFrame {

    /** Creates new form topics */
    public topics() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l2 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        b1 = new javax.swing.JButton();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        l2.setFont(new java.awt.Font("Tahoma", 1, 11));
        l2.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(l2);
        l2.setBounds(10, 260, 280, 20);

        r1.setBackground(new java.awt.Color(0, 0, 102));
        r1.setFont(new java.awt.Font("Tahoma", 1, 11));
        r1.setForeground(new java.awt.Color(255, 255, 0));
        r1.setText("Entertainment Quiz");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        jPanel1.add(r1);
        r1.setBounds(20, 80, 140, 23);

        r2.setBackground(new java.awt.Color(0, 0, 153));
        r2.setFont(new java.awt.Font("Tahoma", 1, 11));
        r2.setForeground(new java.awt.Color(255, 255, 0));
        r2.setText("History Quiz");
        jPanel1.add(r2);
        r2.setBounds(170, 80, 100, 23);

        r3.setBackground(new java.awt.Color(0, 51, 204));
        r3.setFont(new java.awt.Font("Tahoma", 1, 11));
        r3.setForeground(new java.awt.Color(255, 255, 0));
        r3.setText("Sports Quiz");
        jPanel1.add(r3);
        r3.setBounds(280, 80, 100, 23);

        b1.setBackground(new java.awt.Color(0, 0, 204));
        b1.setFont(new java.awt.Font("Tahoma", 1, 11));
        b1.setForeground(new java.awt.Color(255, 255, 0));
        b1.setText("Submit Your Choice");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(50, 170, 150, 23);

        r4.setBackground(new java.awt.Color(0, 0, 102));
        r4.setFont(new java.awt.Font("Tahoma", 1, 11));
        r4.setForeground(new java.awt.Color(255, 255, 0));
        r4.setText("G.K Quiz");
        jPanel1.add(r4);
        r4.setBounds(110, 120, 90, 23);

        r5.setBackground(new java.awt.Color(0, 51, 204));
        r5.setFont(new java.awt.Font("Tahoma", 1, 11));
        r5.setForeground(new java.awt.Color(255, 255, 0));
        r5.setText("Technology Quiz");
        jPanel1.add(r5);
        r5.setBounds(210, 120, 130, 23);

        b2.setBackground(new java.awt.Color(0, 0, 204));
        b2.setFont(new java.awt.Font("Tahoma", 1, 11));
        b2.setForeground(new java.awt.Color(255, 255, 0));
        b2.setText("Move to Questions");
        b2.setEnabled(false);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(220, 170, 140, 23);

        l1.setFont(new java.awt.Font("Tahoma", 1, 11));
        l1.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(l1);
        l1.setBounds(10, 220, 280, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Choose any THREE of the given quiz categories");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 40, 262, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logosah.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(330, 230, 70, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lar1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_r1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        
        if(r1.isSelected()==true && r2.isSelected()==true && r3.isSelected()==true&&r4.isSelected()!=true&&r5.isSelected()!=true) {
            r1.setEnabled(false);
            r2.setEnabled(false);
            r3.setEnabled(false);
            r4.setEnabled(false);
            r5.setEnabled(false);
            l1.setText("Your choices have been submitted successfully.");
        l2.setText("Now you will get question set accordingly.");
        b2.setEnabled(true);
        b1.setEnabled(false);
        }
        else  if(r1.isSelected()==true && r2.isSelected()==true && r4.isSelected()==true&&r3.isSelected()!=true&&r5.isSelected()!=true) {
            r1.setEnabled(false);
            r2.setEnabled(false);
            r3.setEnabled(false);
            r4.setEnabled(false);
            r5.setEnabled(false);
            l1.setText("Your choices have been submitted successfully.");
        l2.setText("Now you will get question set accordingly.");
        b2.setEnabled(true);
        b1.setEnabled(false);
        }
        else if(r1.isSelected()==true && r2.isSelected()==true && r5.isSelected()==true&&r3.isSelected()!=true&&r4.isSelected()!=true) {
            r1.setEnabled(false);
            r2.setEnabled(false);
            r3.setEnabled(false);
            r4.setEnabled(false);
            r5.setEnabled(false);
            l1.setText("Your choices have been submitted successfully.");
        l2.setText("Now you will get question set accordingly.");
        b2.setEnabled(true);
        b1.setEnabled(false);
        }
        else if(r1.isSelected()==true && r3.isSelected()==true && r5.isSelected()==true&&r2.isSelected()!=true&&r4.isSelected()!=true) {
            r1.setEnabled(false);
            r2.setEnabled(false);
            r3.setEnabled(false);
            r4.setEnabled(false);
            r5.setEnabled(false);
            l1.setText("Your choices have been submitted successfully.");
        l2.setText("Now you will get question set accordingly.");
        b2.setEnabled(true);
        b1.setEnabled(false);
        }
        else if(r1.isSelected()==true && r4.isSelected()==true && r5.isSelected()==true&&r3.isSelected()!=true&&r2.isSelected()!=true) {
            r1.setEnabled(false);
            r2.setEnabled(false);
            r3.setEnabled(false);
            r4.setEnabled(false);
            r5.setEnabled(false);
            l1.setText("Your choices have been submitted successfully.");
        l2.setText("Now you will get question set accordingly.");
        b2.setEnabled(true);
        b1.setEnabled(false);
        }
        else if(r1.isSelected()==true && r4.isSelected()==true && r3.isSelected()==true&&r2.isSelected()!=true&&r5.isSelected()!=true) {
            r1.setEnabled(false);
            r2.setEnabled(false);
            r3.setEnabled(false);
            r4.setEnabled(false);
            r5.setEnabled(false);
            l1.setText("Your choices have been submitted successfully.");
        l2.setText("Now you will get question set accordingly.");
        b2.setEnabled(true);
        b1.setEnabled(false);
        }
        else  if(r5.isSelected()==true && r2.isSelected()==true && r3.isSelected()==true&&r1.isSelected()!=true&&r4.isSelected()!=true) {
            r1.setEnabled(false);
            r2.setEnabled(false);
            r3.setEnabled(false);
            r4.setEnabled(false);
            r5.setEnabled(false);
            l1.setText("Your choices have been submitted successfully.");
        l2.setText("Now you will get question set accordingly.");
        b2.setEnabled(true);
        b1.setEnabled(false);
        }
        else if(r4.isSelected()==true && r2.isSelected()==true && r5.isSelected()==true&&r1.isSelected()!=true&&r3.isSelected()!=true) {
            r1.setEnabled(false);
            r2.setEnabled(false);
            r3.setEnabled(false);
            r4.setEnabled(false);
            r5.setEnabled(false);
            l1.setText("Your choices have been submitted successfully.");
        l2.setText("Now you will get question set accordingly.");
        b2.setEnabled(true);
        b1.setEnabled(false);
        }
        else if(r5.isSelected()==true && r4.isSelected()==true && r3.isSelected()==true&&r1.isSelected()!=true&&r2.isSelected()!=true) {
            r1.setEnabled(false);
            r2.setEnabled(false);
            r3.setEnabled(false);
            r4.setEnabled(false);
            r5.setEnabled(false);
            l1.setText("Your choices have been submitted successfully.");
        l2.setText("Now you will get question set accordingly.");
        b2.setEnabled(true);
        b1.setEnabled(false);
        }
        else if(r4.isSelected()==true && r2.isSelected()==true && r3.isSelected()==true&&r1.isSelected()!=true&&r5.isSelected()!=true) {
            r1.setEnabled(false);
            r2.setEnabled(false);
            r3.setEnabled(false);
            r4.setEnabled(false);
            r5.setEnabled(false);
            l1.setText("Your choices have been submitted successfully.");
        l2.setText("Now you will get question set accordingly.");
        b2.setEnabled(true);
        b1.setEnabled(false);
        }

        else
        {
           l1.setText("You made invalid number of choices");
           l2.setText("Please select 3 choices only");
        }
}//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(r1.isSelected()==true && r2.isSelected()==true && r3.isSelected()==true) {
            new ques11().setVisible(true);
            dispose();
        }
        if(r1.isSelected()==true && r2.isSelected()==true && r4.isSelected()==true) {
            new ques21().setVisible(true);
            dispose();
        }
        if(r1.isSelected()==true && r2.isSelected()==true && r5.isSelected()==true) {
            new ques31().setVisible(true);
            dispose();
        }
        if(r1.isSelected()==true && r3.isSelected()==true && r5.isSelected()==true) {
            new ques41().setVisible(true);
            dispose();
        }
        if(r1.isSelected()==true && r4.isSelected()==true && r5.isSelected()==true) {
            new ques51().setVisible(true);
            dispose();
        }
        if(r1.isSelected()==true && r3.isSelected()==true && r4.isSelected()==true) {
            new ques61().setVisible(true);
            dispose();
        }
        if(r2.isSelected()==true && r3.isSelected()==true && r5.isSelected()==true) {
            new ques71().setVisible(true);
            dispose();
        }
        if(r2.isSelected()==true && r4.isSelected()==true && r5.isSelected()==true) {
            new ques81().setVisible(true);
            dispose();
        }
        if(r2.isSelected()==true && r3.isSelected()==true && r4.isSelected()==true) {
            new ques91().setVisible(true);
            dispose();
        }
        if(r3.isSelected()==true && r4.isSelected()==true && r5.isSelected()==true) {
            new Q01().setVisible(true);
            dispose();
        }
}//GEN-LAST:event_b2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new topics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    // End of variables declaration//GEN-END:variables

}
