
import gentechquiz.Main;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ty.java
 *
 * Created on Nov 1, 2017, 8:53:54 PM
 */

/**
 *
 * @author Admin
 */
public class ty extends javax.swing.JFrame {

    /** Creates new form ty */
    public ty() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Thanks For Playing.");

        jLabel2.setText("Hope You Had a Nice Learning Experience");

        b2.setText("Play Again");
        b2.setEnabled(false);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setText("Exit");
        b3.setEnabled(false);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b1.setText("Obtain Score");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel3.setText("Developers Team");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Yogansh Gupta");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Shashwat Singh");

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel6.setText("(KIET 3rd year IT-B)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel2)
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(b1)
                                .addGap(29, 29, 29)
                                .addComponent(b2)
                                .addGap(45, 45, 45)
                                .addComponent(b3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b3)
                    .addComponent(b2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
b1.setEnabled(false);
b2.setEnabled(true);
b3.setEnabled(true);

l9.setText("Correct Answers given = "+Main.m);

if(Main.a!=0)
{
if(Main.m>=3&&Main.m<6)
{
    l7.setText("Bonus point earned is 1");
    Main.a=Main.a+1;
}
if(Main.m>=6&&Main.m<10)
{
    l7.setText("Bonus point earned is 2");
    Main.a=Main.a+2;
}
if(Main.m==10)
{
    l7.setText("Bonus point earned is 3");
    Main.a=Main.a+3;
}
l5.setText("Your total score in this session = "+Main.a);
Main.a=0;
Main.m=0;
}


if(Main.b!=0)
{
if(Main.m>=3&&Main.m<6)
{
    l7.setText("Bonus point earned is 1");
    Main.b=Main.b+1;
}
if(Main.m>=6&&Main.m<10)
{
    l7.setText("Bonus point earned is 2");
    Main.b=Main.b+2;
}
if(Main.m==10)
{
    l7.setText("Bonus point earned is 3");
    Main.b=Main.b+3;
}
l5.setText("Your total score in this session = "+Main.b);
Main.b=0;
Main.m=0;
}


if(Main.c!=0)
{
    if(Main.m>=3&&Main.m<6)
{
    l7.setText("Bonus point earned is 1");
    Main.c=Main.c+1;
}
if(Main.m>=6&&Main.m<10)
{
    l7.setText("Bonus point earned is 2");
    Main.c=Main.c+2;
}
if(Main.m==10)
{
    l7.setText("Bonus point earned is 3");
    Main.c=Main.c+3;
}
l5.setText("Your total score in this session = "+Main.c);
Main.c=0;
Main.m=0;
}


if(Main.d!=0)
{
    if(Main.m>=3&&Main.m<6)
{
    l7.setText("Bonus point earned is 1");
    Main.d=Main.d+1;
}
if(Main.m>=6&&Main.m<10)
{
    l7.setText("Bonus point earned is 2");
    Main.d=Main.d+2;
}
if(Main.m==10)
{
    l7.setText("Bonus point earned is 3");
    Main.d=Main.d+3;
}
l5.setText("Your total score in this session = "+Main.d);
Main.d=0;
Main.m=0;
}


if(Main.e!=0)
{
    if(Main.m>=3&&Main.m<6)
{
    l7.setText("Bonus point earned is 1");
    Main.e=Main.e+1;
}
if(Main.m>=6&&Main.m<10)
{
    l7.setText("Bonus point earned is 2");
    Main.e=Main.e+2;
}
if(Main.m==10)
{
    l7.setText("Bonus point earned is 3");
    Main.e=Main.e+3;
}
l5.setText("Your total score in this session = "+Main.e);
Main.e=0;
Main.m=0;
}


if(Main.f!=0)
{
    if(Main.m>=3&&Main.m<6)
{
    l7.setText("Bonus point earned is 1");
    Main.f=Main.f+1;
}
if(Main.m>=6&&Main.m<10)
{
    l7.setText("Bonus point earned is 2");
    Main.f=Main.f+2;
}
if(Main.m==10)
{
    l7.setText("Bonus point earned is 3");
    Main.f=Main.f+3;
}
l5.setText("Your total score in this session = "+Main.f);
Main.f=0;
Main.m=0;
}


if(Main.g!=0)
{
    if(Main.m>=3&&Main.m<6)
{
    l7.setText("Bonus point earned is 1");
    Main.g=Main.g+1;
}
if(Main.m>=6&&Main.m<10)
{
    l7.setText("Bonus point earned is 2");
    Main.g=Main.g+2;
}
if(Main.m==10)
{
    l7.setText("Bonus point earned is 3");
    Main.g=Main.g+3;
}
l5.setText("Your total score in this session = "+Main.g);
Main.g=0;
Main.m=0;
}


if(Main.h!=0)
{
    if(Main.m>=3&&Main.m<6)
{
    l7.setText("Bonus point earned is 1");
    Main.h=Main.h+1;
}
if(Main.m>=6&&Main.m<10)
{
    l7.setText("Bonus point earned is 2");
    Main.h=Main.h+2;
}
if(Main.m==10)
{
    l7.setText("Bonus point earned is 3");
    Main.h=Main.h+3;
}
l5.setText("Your total score in this session = "+Main.h);
Main.h=0;
Main.m=0;
}


if(Main.i!=0)
{
    if(Main.m>=3&&Main.m<6)
{
    l7.setText("Bonus point earned is 1");
    Main.i=Main.i+1;
}
if(Main.m>=6&&Main.m<10)
{
    l7.setText("Bonus point earned is 2");
    Main.i=Main.i+2;
}
if(Main.m==10)
{
    l7.setText("Bonus point earned is 3");
    Main.i=Main.i+3;
}
l5.setText("Your total score in this session = "+Main.i);
Main.i=0;
Main.m=0;
}


if(Main.j!=0)
{
    if(Main.m>=3&&Main.m<6)
{
    l7.setText("Bonus point earned is 1");
    Main.j=Main.j+1;
}
if(Main.m>=6&&Main.m<10)
{
    l7.setText("Bonus point earned is 2");
    Main.j=Main.j+2;
}
if(Main.m==10)
{
    l7.setText("Bonus point earned is 3");
    Main.j=Main.j+3;
}
l5.setText("Your total score in this session = "+Main.j);
Main.j=0;
Main.m=0;
}


}//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_b3ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
      new face().setVisible(true);
      dispose();

    }//GEN-LAST:event_b2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables

}
